---
new_page_extension: md
auto_deploy: false
admin_path: "/public/admin-cms"
webhook_url: 
sections:
- type: directory
  path: src/pages
  label: Pages
  create: all
  match: "**/*"
upload_dir: public/images/uploads
public_path: "/images/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: dist
  install_dependencies_command: npm install
  preview_docker_image: node:16.13.0
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run dev
